[tools]
# https://github.com/oven-sh/bun/releases
bun = "1.3.2"
# https://github.com/biomejs/biome/releases
biome = "2.3.5"
# https://github.com/evilmartians/lefthook/releases
lefthook = "2.0.0"
# https://github.com/golangci/golangci-lint/releases
golangci-lint = "2.6.1"
# https://github.com/grafana/grizzly/releases
"github:grafana/grizzly" = "0.7.1"
# https://github.com/grafana/grafanactl/releases
"github:grafana/grafanactl" = "0.1.6"
